version: "3.3"
services:
  mysql:
    image: mysql:local
    container_name: sql
    build: .
    volumes:
      - ./init:/docker-entrypoint-initdb.d/:ro
      - /data/mysql/data:/var/lib/mysql
      - ./sql:/opt/sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    secrets:
      - db_root_password
secrets:
  db_root_password:
    file: db_root_password.txt
