version: "3.1"
services:
  mysql:
    image: mysql:local
    container_name: sql # stack  不支持
    build: . # stack  不支持
    volumes:
      - ./init:/docker-entrypoint-initdb.d/:ro
      - /data/mysql:/var/lib/mysql
      - ./sql:/opt/sql:ro
    secrets:
      - db_root_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped # stack  不支持
    deploy:
      mode: replicated
      replicas: 1
      # placement:
      #   constraints:
      #     - "node.labels.role == data"
      restart_policy:
        condition: on-failure
        delay: 5s
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
secrets:
  db_root_password:
    file: db_root_password.txt
    #external: true  # docker-compose 不支持
